services:
  - type: web
    name: automatic-tagging-system-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    startCommand: npm run preview
    envVars:
      - key: PORT
        value: 5173
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
